# Generated by Django 4.2.5 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofule',
            name='mark',
            field=models.CharField(default='', max_length=260),
        ),
    ]
